Repository yaito3014/yk_util, pull requests merged in 2025-05, with the labels that each got.

#60 Fix throwt
  include/yk/throwt.hpp
  test/CMakeLists.txt
  test/main.cpp
  test/test_utility.cpp
  test/test_utility.hpp
Labels: bug

#62 yk_util v0.2.0 (drop C++20 & GCC 13)
  .github/workflows/run_test.yml
  CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, CI

#63 Skip man page generation
  .github/workflows/run_test.yml
Labels: enhancement, CI

#43 MPMC task scheduler (yk::exec::scheduler)
  .gitignore
  include/yk/arch.hpp
  include/yk/chrono.hpp
  include/yk/concurrent_deque.hpp
  include/yk/concurrent_pool.hpp
  include/yk/concurrent_vector.hpp
  include/yk/exec/atomic_queue.hpp
  include/yk/exec/cv_deque.hpp
  include/yk/exec/cv_inplace_vector.hpp
  include/yk/exec/cv_queue.hpp
  include/yk/exec/cv_queue_types.hpp
  include/yk/exec/cv_vector.hpp
  include/yk/exec/debug.hpp
  include/yk/exec/port/boost_lockfree_queue.hpp
  include/yk/exec/port/boost_lockfree_stack.hpp
  include/yk/exec/port/detail/boost_lockfree_common.hpp
  include/yk/exec/queue_gate.hpp
  include/yk/exec/queue_traits.hpp
  include/yk/exec/scheduler.hpp
  include/yk/exec/scheduler_delta_stats.hpp
  include/yk/exec/scheduler_stats.hpp
  include/yk/exec/scheduler_stats_tracker.hpp
  include/yk/exec/scheduler_traits.hpp
  include/yk/exec/thread_index.hpp
  include/yk/exec/worker_pool.hpp
  include/yk/exec/worker_types.hpp
  include/yk/inplace_vector.hpp
  include/yk/interrupt_exception.hpp
  include/yk/no_unique_address.hpp
  test/CMakeLists.txt
  test/atomic_queue.cpp
  test/concurrency.cpp
  test/scheduler.cpp
Labels: enhancement

#66 add lifetimebound attribute
  include/yk/lifetimebound.hpp
  include/yk/util/reverse.hpp
  include/yk/variant_view/variant_view.hpp
  test/variant_view.cpp
Labels: enhancement

#68 Update cpp warning notifier
  .github/workflows/run_test.yml
  include/yk/throwt.hpp
Labels: enhancement, CI

#72 add perfect_forward_as_tuple
  include/yk/util/perfect_forward_as_tuple.hpp
  test/meta.cpp
Labels: enhancement

#76 remove yk::to_underlying
  include/yk/enum_bitops.hpp
  include/yk/enum_bitops_algorithm.hpp
  include/yk/enum_bitops_io.hpp
  include/yk/exec/cv_queue.hpp
  include/yk/util/to_underlying.hpp
  test/enum_bitops.cpp
Labels: enhancement

#75 colorizing utility
  include/yk/colorize.hpp
  include/yk/print.hpp
  test/CMakeLists.txt
  test/colorize.cpp
Labels: enhancement

#82 Temporarily disable UBSan on GCC
  test/CMakeLists.txt
Labels: CI, upstream-workaround

#69 comparison utilities
  include/yk/boolean_testable.hpp
  include/yk/compare.hpp
  include/yk/compare/adaptor.hpp
  include/yk/compare/comparator.hpp
  include/yk/compare/concepts.hpp
  include/yk/util/functional.hpp
  include/yk/util/type_list.hpp
  test/CMakeLists.txt
  test/compare.cpp
  test/meta.cpp
Labels: enhancement

#83 Correctly promote `partial | promote(partial)`
  include/yk/compare/comparator.hpp
  test/compare.cpp
Labels: bug

#84 Suppress yk::exec related debug outputs in unit tests
  include/yk/exec/debug.hpp
  include/yk/exec/scheduler.hpp
  test/scheduler.cpp
Labels: enhancement
