Repository yaito3014/yk_util, pull requests merged in 2025-04, with the labels that each got.

#38 Reorganize enum utilities
  include/yk/bitmask_enum.hpp
  include/yk/enum_bitops.hpp
  include/yk/enum_bitops_algorithm.hpp
  include/yk/enum_bitops_io.hpp
  test/test.cpp
Labels: enhancement

#40 Implement concurrent_pool
  include/yk/concurrent_deque.hpp
  include/yk/concurrent_pool.hpp
  include/yk/concurrent_vector.hpp
  include/yk/interrupt_exception.hpp
  test/test.cpp
Labels: enhancement, help wanted

#52 macronize noreturn
  include/yk/throwt.hpp
Labels: bug

#51 throwt print util
  include/yk/detail/traced_type.hpp
  include/yk/printt.hpp
  include/yk/throwt.hpp
  test/main.cpp
Labels: enhancement

#53 install cpp-warning-notifier
  .github/workflows/run_test.yml
  include/yk/throwt.hpp
  test/main.cpp
Labels: enhancement, CI

#59 Fix unreachable code warning on throwt test
  include/yk/throwt.hpp
  test/CMakeLists.txt
  test/main.cpp
  test/test_utility.cpp
  test/test_utility.hpp
Labels: bug, CI
